services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
      - ./certs/mosquitto:/mosquitto/certs:ro
    networks:
      - eleados_network
    
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin   # CHANGE!!!
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./postgresql/sql:/etc/eleados
    networks:
      - eleados_network

  eleados_event_service:
    container_name: eleados_event_service
    restart: unless-stopped
    build:
      context: ./event_service
      dockerfile: ./Dockerfile

    environment:
      MOSQUITTO_HOSTNAME: mosquitto
      MOSQUITTO_PORT: 8883
      MOSQUITTO_DYNSEC_USERNAME: admin
      MOSQUITTO_DYNSEC_PASSWORD: admin    # CHANGE!!!

    volumes:
      - ./event_service/logs:/var/log/eleados
      - ./certs/event_service:/srv/eleados/certs:ro
    networks:
      - eleados_network

networks: 
  eleados_network:
    driver: bridge
