#!/bin/bash


echo -e "--- Might require sudo if it can't find files or you have to generate them ---"

SERVER_ROLE="$SERVER_MQTT_USERNAME""_role"


mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec createClient $SERVER_MQTT_USERNAME  || exit 1
mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec createRole $SERVER_ROLE  || exit 2


mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec addRoleACL $SERVER_ROLE subscribePattern "reader/#" allow 5  || exit 3
mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec addRoleACL $SERVER_ROLE publishClientSend "reader/#" allow 5  || exit 3

mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec addRoleACL $SERVER_ROLE subscribePattern "registrator/#" allow 5  || exit 3
mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec addRoleACL $SERVER_ROLE publishClientSend "registrator/#" allow 5  || exit 3

mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec addRoleACL $SERVER_ROLE subscribePattern "whitelist/#" allow 5  || exit 4
mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec addRoleACL $SERVER_ROLE publishClientSend "whitelist/#" allow 5  || exit 4


mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec addClientRole $SERVER_MQTT_USERNAME $SERVER_ROLE 5  || exit 5
mosquitto_ctrl --cafile $MOSQUITTO_CA_FILE_PATH --cert $SERVER_CERT_FILE_PATH --key $SERVER_KEY_FILE_PATH -u $MOSQUITTO_DYNSEC_USERNAME -h $MOSQUITTO_HOSTNAME -P $MOSQUITTO_DYNSEC_PASSWORD dynsec addClientRole $SERVER_MQTT_USERNAME $MOSQUITTO_DYNSEC_USERNAME 5  || exit 5

